# Setup node version
FROM node:18

# SET Node memory limit
RUN export NODE_OPTIONS="--max-old-space-size=2048"

# Set the working directory
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json files
COPY package\*.json ./
COPY server.ts ./

# Install the dependencies
RUN npm install --legacy-peer-deps

# Copy the rest of the application code
COPY . .

# build app
RUN npm run build:prod

# expose local port
EXPOSE 8080
ENV PORT 8080
ENV HOST 0.0.0.0

# start server
CMD npm run serve:ssr