export const APP_SETTINGS = {
  EMPTY_LINE: '',
  FIRST_INDEX: 0,
  MONTHS_ABBREVIATIONS: [
    'IAN',
    'FEB',
    'MAR',
    'APR',
    'MAI',
    'IUN',
    'IUL',
    'AUG',
    'SEP',
    'OCT',
    'NOI',
    'DEC',
  ],
  DOT_SEPARATOR: '.',
  RO_LOCALE_FORMAT: 'ro-RO',
  DEFAULT_MAP_OPTIONS: {
    mapId: 'a3b3a26d13f3f14f',
    center: { lat: 45.9418997, lng: 25.0200795 },
    zoom: 12,
    fullscreenControl: true,
    scrollwheel: false,
    streetViewControl: false,
  },
  RATING: {
    RATING_VALUE: 0,
    RATING_DISPLAY: true,
    STAR_WIDTH: '20px',
    RATING_FONT_SIZE: '16px',
  },
};
